#!/usr/bin/env python

import numpy as np
import os, sys, time

from xaosim.shmlib import shm


dms = 11            # DM size in actuators
xdm,ydm = np.meshgrid(np.arange(dms)-dms/2, np.arange(dms)-dms/2)
disp = shm('/tmp/dmdisp6.im.shm', verbose=False)

argvs = sys.argv[1:]

try:
    myx = float(argvs[0])
except:
    myx = 0.0

try:
    myy = float(argvs[1])
except:
    myy = 0.0

print("myx = %.2f, myy = %.2f" % (myx, myy))

tptlt = 0.01 * (myx * xdm + myy * ydm)

disp.set_data(tptlt.T.astype(np.float32))
time.sleep(0.1)

#disp.close()

